FROM python:3.12-slim
WORKDIR /app
COPY scripts/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/users_db_simulate.py /app/users_db_simulate.py
COPY scripts/songs_db_simulate.py /app/songs_db_simulate.py
COPY scripts/subscriptions_db_simulate.py /app/subscriptions_db_simulate.py